# Project: keylogger
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = keylogger_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Programme/Dev-Cpp/lib"  -mwindows -s 
INCS =  -I"C:/Programme/Dev-Cpp/include" 
CXXINCS =  -I"C:/Programme/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Programme/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Programme/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Programme/Dev-Cpp/include/c++/3.4.2"  -I"C:/Programme/Dev-Cpp/include" 
BIN  = keylogger.exe
CXXFLAGS = $(CXXINCS)   -O3 -mwindows
CFLAGS = $(INCS)   -O3 -mwindows
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before keylogger.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "keylogger.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

keylogger_private.res: keylogger_private.rc 
	$(WINDRES) -i keylogger_private.rc --input-format=rc -o keylogger_private.res -O coff 
