name: Keylogger

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        zig-version:
          - '0.15.1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check Zig version
        run: zig version

      - name: Build
        run: zig build --verbose --summary all --release -Dci=true

      - name: Check help
        run: ./zig-out/bin/keylogger.exe --help
